### ISSUE TITLE
rsaCheck 不应该 omit sign_type

### ISSUE THREAD

**Issue by benvirus** [cynosures/alipay-sdk-node#5]
如题：
rsaCheck 方法内，不应该 omit sign_type, 现在是跑不同的。不知道你们是怎么在生产环境使用的。

**Comment by yolopunk** [comment]
@benvirus 

[异步返回结果的验签](https://opendocs.alipay.com/open/203/105286)

* 第一步： 在通知返回参数列表中，除去sign、sign_type两个参数外，凡是通知返回回来的参数皆是待验签的参数。

文档里这么写的。线上使用是有问题吗？麻烦告知一下详情 多谢🙂

**Comment by benvirus** [comment]
@yolopunk 
文档写错了。
omit sign_type 之后，结果是 false.
只 omit sign ，结果就是 true.

**Comment by benvirus** [comment]
哦，我知道了。H5 和 生活号的是不一样的。找到如下[文档](https://opendocs.alipay.com/open/200/106120#%E5%BC%82%E6%AD%A5%E9%80%9A%E7%9F%A5%E9%AA%8C%E7%AD%BE)：
![image](https://user-images.githubusercontent.com/13535932/80167539-39c60200-8613-11ea-847e-485b45564560.png)

**Comment by benvirus** [comment]
开放平台的文档真他妈跟迷一样

**Comment by yolopunk** [comment]
> 开放平台的文档真他妈跟迷一样

哈哈哈 是的 几年前写的时候也是摸不着头脑 现在文档和以前比已经算是进步了不少了
